### ISSUE TITLE
VulInfo needs a license

### ISSUE THREAD

**Issue by DennisClark** [PAGalaxyLab/VulInfo#4]
Please declare a license for VulInfo so that users can use it in their own projects. Thanks very much!  

If you would like suggestions, those can be provided.

**Comment by rk700** [comment]
Added

https://github.com/PAGalaxyLab/VulInfo/commit/d55a85e66a692fdce45375e831c58c2a7161e0d2

**Comment by DennisClark** [comment]
Perfect, thank you!
